Document: cpusb
Title: Debian cpusb Manual
Author: <insert document author here>
Abstract: This manual describes what cpusb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cpusb/cpusb.sgml.gz

Format: postscript
Files: /usr/share/doc/cpusb/cpusb.ps.gz

Format: text
Files: /usr/share/doc/cpusb/cpusb.text.gz

Format: HTML
Index: /usr/share/doc/cpusb/html/index.html
Files: /usr/share/doc/cpusb/html/*.html
